### ISSUE TITLE
Return correct orderID

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#67]
We tested on our side without the woocommerce plugin and it works fine.
We tested with the new woocommerce plugin and it does not work unless you are using an older version. 

The notes my college took on the issue can be found below:

When it works; an updateCheckout request have been sent with new order number from store.
When it does not work; an updateCheckout request have not been sent when order number.

When testing through master branch the orderid never gets updated from the temporary orderid.

When testing using an older branch: 0b3a5be70d16ba5c367b55ba7856a56513511bdd as long as you wait for the checkout to load completely before continuing, it works fine, orderid gets updated.
However on this older branch, if you do not wait a little until checkout has loaded completely, we get the same issue that orderid does not get updated.

Note that orderid always gets updated in mexccustumerorders, it is only in mexcCustomerinvoice_tests it does not always gets updated.

**Comment by NiklasHogefjord** [comment]
@OskarOstlund Perhaps you can test again with the current master branch?

Billmate needed to do a change in the [purchase_initialized](https://billmate.github.io/api-docs/#purchase_initialized) frontend JS event. We have also done a change in the plugin code since the response to this callback now should be replied with [purchase_complete](https://billmate.github.io/api-docs/#purchase_complete).

**Comment by NiklasHogefjord** [comment]
@OskarOstlund I have tested and can confirm that invoice payment, card payment and direct bank payment works. Can you confirm this as well?

**Comment by andyjohansson** [comment]
What is the status here @OskarOstlund ?

**Comment by OskarOstlund** [comment]
Tested and approved.
